kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /go
  path: src/github.com/ipfs/ipget

steps:
  - name: myclone
    image: docker:git
    commands:
      - git clone -b ${DRONE_TAG:-master} https://github.com/ipfs/ipget.git $DRONE_WORKSPACE

  - name: deps
    image: golang:1.12.4
    commands:
      - make deps
      - |
        cat <<EOF >Dockerfile
        FROM scratch
        COPY ipget /usr/bin/
        ENTRYPOINT ["ipget"]
        EOF

  - name: amd64
    image: golang:1.12.4
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build -o amd64/ipget -ldflags='-s -w'
      - cp Dockerfile amd64/

  - name: docker-amd64
    image: plugins/docker
    settings:
      context: amd64
      repo: quay.io/anguslees/ipget
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

  - name: armv6
    image: golang:1.12.4
    environment:
      GOOS: linux
      GOARCH: arm
      GOARM: 6
      CGO_ENABLED: 0
    commands:
      - go build -o armv6/ipget -ldflags='-s -w'
      - cp Dockerfile armv6/

  - name: docker-armv6
    image: plugins/docker
    settings:
      context: armv6
      repo: quay.io/anguslees/ipget
      auto_tag: true
      auto_tag_suffix: linux-arm-v6
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

  - name: armv7
    image: golang:1.12.4
    environment:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      CGO_ENABLED: 0
    commands:
      - go build -o armv7/ipget -ldflags='-s -w'
      - cp Dockerfile armv7/

  - name: docker-armv7
    image: plugins/docker
    settings:
      context: armv7
      repo: quay.io/anguslees/ipget
      auto_tag: true
      auto_tag_suffix: linux-arm-v7
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

  - name: arm64
    image: golang:1.12.4
    environment:
      GOOS: linux
      GOARCH: arm64
      CGO_ENABLED: 0
    commands:
      - go build -o arm64/ipget -ldflags='-s -w'
      - cp Dockerfile arm64/

  - name: docker-arm64
    image: plugins/docker
    settings:
      context: arm64
      repo: quay.io/anguslees/ipget
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

  - name: manifest
    image: plugins/manifest
    settings:
      target: quay.io/anguslees/ipget
      template: quay.io/anguslees/ipget:OS-ARCH-VARIANT
      platforms:
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

  - name: publish
    image: plugins/docker
    settings:
      repo: quay.io/anguslees/ipget
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
