---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

workspace:
  base: /go
  path: src/github.com/ipfs/ipget

steps:
- name: myclone
  image: docker:git@sha256:d7f576652c05a6e86970cbdb477d4bb5d30932599806786e126067e406ef59cb
  commands:
  - "git clone -b ${DRONE_TAG:-master} https://github.com/ipfs/ipget.git $DRONE_WORKSPACE"

- name: deps
  image: golang:1.17.1@sha256:c9fbf6d2c4730573ba487805e859bc80239af1985641c7b031bff046b51f60db
  commands:
  - make deps
  - "cat <<EOF >Dockerfile\nFROM scratch\nARG BIN=ipget\nLABEL \\\\\n org.opencontainers.image.revision=$DRONE_COMMIT_SHA \\\\\n org.opencontainers.image.authors=\"$DRONE_COMMIT_AUTHOR_EMAIL\" \\\\\n org.opencontainers.image.url=https://github.com/ipfs/ipget \\\\\n org.opencontainers.image.source=https://github.com/ipfs/ipget.git \\\\\n org.opencontainers.image.version=$DRONE_TAG\nCOPY \\\\$$BIN /usr/bin/ipget\nENTRYPOINT [\"ipget\"]\nEOF\n"

- name: amd64
  image: golang:1.17.1@sha256:c9fbf6d2c4730573ba487805e859bc80239af1985641c7b031bff046b51f60db
  commands:
  - "go build -ldflags='-s -w -extldflags=-static' -tags netgo -installsuffix netgo -o ipget.amd64"
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux

- name: arm64
  image: golang:1.17.1@sha256:c9fbf6d2c4730573ba487805e859bc80239af1985641c7b031bff046b51f60db
  commands:
  - "go build -ldflags='-s -w -extldflags=-static' -tags netgo -installsuffix netgo -o ipget.arm64"
  environment:
    CGO_ENABLED: 0
    GOARCH: arm64
    GOOS: linux

- name: armv6
  image: golang:1.17.1@sha256:c9fbf6d2c4730573ba487805e859bc80239af1985641c7b031bff046b51f60db
  commands:
  - "go build -ldflags='-s -w -extldflags=-static' -tags netgo -installsuffix netgo -o ipget.armv6"
  environment:
    CGO_ENABLED: 0
    GOARCH: arm
    GOARM: 6
    GOOS: linux

- name: armv7
  image: golang:1.17.1@sha256:c9fbf6d2c4730573ba487805e859bc80239af1985641c7b031bff046b51f60db
  commands:
  - "go build -ldflags='-s -w -extldflags=-static' -tags netgo -installsuffix netgo -o ipget.armv7"
  environment:
    CGO_ENABLED: 0
    GOARCH: arm
    GOARM: 7
    GOOS: linux

- name: docker-amd64
  image: banzaicloud/drone-kaniko@sha256:3800666733beed5c0709cf9cf759a9f7858c596b5a08d9e71a657db7c31f05b9
  settings:
    build_args:
    - BIN=ipget.amd64
    log: debug
    password:
      from_secret: docker_password
    registry: quay.io
    repo: quay.io/anguslees/ipget
    tags: "${DRONE_COMMIT_SHA}-linuxamd64"
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: docker-arm64
  image: banzaicloud/drone-kaniko@sha256:3800666733beed5c0709cf9cf759a9f7858c596b5a08d9e71a657db7c31f05b9
  settings:
    build_args:
    - BIN=ipget.arm64
    log: debug
    password:
      from_secret: docker_password
    registry: quay.io
    repo: quay.io/anguslees/ipget
    tags: "${DRONE_COMMIT_SHA}-linuxarm64"
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: docker-armv6
  image: banzaicloud/drone-kaniko@sha256:3800666733beed5c0709cf9cf759a9f7858c596b5a08d9e71a657db7c31f05b9
  settings:
    build_args:
    - BIN=ipget.armv6
    log: debug
    password:
      from_secret: docker_password
    registry: quay.io
    repo: quay.io/anguslees/ipget
    tags: "${DRONE_COMMIT_SHA}-linuxarm6"
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: docker-armv7
  image: banzaicloud/drone-kaniko@sha256:3800666733beed5c0709cf9cf759a9f7858c596b5a08d9e71a657db7c31f05b9
  settings:
    build_args:
    - BIN=ipget.armv7
    log: debug
    password:
      from_secret: docker_password
    registry: quay.io
    repo: quay.io/anguslees/ipget
    tags: "${DRONE_COMMIT_SHA}-linuxarm7"
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: manifest
  image: plugins/manifest@sha256:05930eefaba35a6f1a4225b3ce2cbb6a71ed31d02995d83e49c8b4ec4a3e78a7
  settings:
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm/6
    - linux/arm/7
    registry: quay.io
    repo: quay.io/anguslees/ipget
    template: "quay.io/anguslees/ipget:${DRONE_COMMIT_SHA}-OSARCHVARIANT"
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

...
